# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.3.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_api
from eve_api.models.post_fleets_fleet_id_wings_created import PostFleetsFleetIdWingsCreated  # noqa: E501
from eve_api.rest import ApiException


class TestPostFleetsFleetIdWingsCreated(unittest.TestCase):
    """PostFleetsFleetIdWingsCreated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostFleetsFleetIdWingsCreated(self):
        """Test PostFleetsFleetIdWingsCreated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_api.models.post_fleets_fleet_id_wings_created.PostFleetsFleetIdWingsCreated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
