# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.3.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_api
from eve_api.models.get_corporations_corporation_id_wallets200_ok import GetCorporationsCorporationIdWallets200Ok  # noqa: E501
from eve_api.rest import ApiException


class TestGetCorporationsCorporationIdWallets200Ok(unittest.TestCase):
    """GetCorporationsCorporationIdWallets200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCorporationsCorporationIdWallets200Ok(self):
        """Test GetCorporationsCorporationIdWallets200Ok"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_api.models.get_corporations_corporation_id_wallets200_ok.GetCorporationsCorporationIdWallets200Ok()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
