# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.3.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_api
from eve_api.models.get_wars_war_id_killmails_unprocessable_entity import GetWarsWarIdKillmailsUnprocessableEntity  # noqa: E501
from eve_api.rest import ApiException


class TestGetWarsWarIdKillmailsUnprocessableEntity(unittest.TestCase):
    """GetWarsWarIdKillmailsUnprocessableEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetWarsWarIdKillmailsUnprocessableEntity(self):
        """Test GetWarsWarIdKillmailsUnprocessableEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_api.models.get_wars_war_id_killmails_unprocessable_entity.GetWarsWarIdKillmailsUnprocessableEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
