# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.3.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_api
from eve_api.api.clones_api import ClonesApi  # noqa: E501
from eve_api.rest import ApiException


class TestClonesApi(unittest.TestCase):
    """ClonesApi unit test stubs"""

    def setUp(self):
        self.api = eve_api.api.clones_api.ClonesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_characters_character_id_clones(self):
        """Test case for get_characters_character_id_clones

        Get clones  # noqa: E501
        """
        pass

    def test_get_characters_character_id_implants(self):
        """Test case for get_characters_character_id_implants

        Get active implants  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
